/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}', './pages/**/*.html'],
  theme: {
    extend: {
      colors: {
        background: '#101221',
        surface: '#101221',
        'surface-dim': '#101221',
        'surface-bright': '#363848',
        'surface-container-lowest': '#0b0d1b',
        'surface-container-low': '#191b29',
        'surface-container': '#1d1f2d',
        'surface-container-high': '#272938',
        'surface-container-highest': '#323443',
        'surface-variant': '#323443',
        'surface-tint': '#d0bcff',
        primary: '#d0bcff',
        'primary-container': '#a078ff',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        secondary: '#ffb95f',
        'secondary-container': '#ee9800',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#ffb95f',
        tertiary: '#ffb869',
        'tertiary-container': '#ca801e',
        'tertiary-fixed': '#ffdcbb',
        'tertiary-fixed-dim': '#ffb869',
        outline: '#958ea0',
        'outline-variant': '#494454',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-background': '#e1e1f5',
        'on-surface': '#e1e1f5',
        'on-surface-variant': '#cbc3d7',
        'on-primary': '#3c0091',
        'on-primary-container': '#340080',
        'on-primary-fixed': '#23005c',
        'on-primary-fixed-variant': '#5516be',
        'on-secondary': '#472a00',
        'on-secondary-container': '#5b3800',
        'on-secondary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#653e00',
        'on-tertiary': '#482900',
        'on-tertiary-container': '#3f2300',
        'on-tertiary-fixed': '#2c1700',
        'on-tertiary-fixed-variant': '#673d00',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e1e1f5',
        'inverse-on-surface': '#2e2f3f',
        'inverse-primary': '#6d3bd7',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1200px',
        gutter: '1.5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        'section-gap': '4rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      boxShadow: {
        'primary-glow': '0 0 20px rgba(139, 92, 246, 0.3)',
        'gold-glow': '0 0 20px rgba(245, 158, 11, 0.24)',
        glass: '0 24px 60px rgba(11, 13, 27, 0.45)',
      },
      backgroundImage: {
        'mystic-radial':
          'radial-gradient(circle at top, rgba(208, 188, 255, 0.16), transparent 36%), radial-gradient(circle at 80% 20%, rgba(255, 185, 95, 0.12), transparent 28%), linear-gradient(180deg, rgba(11, 13, 27, 1) 0%, rgba(16, 18, 33, 1) 100%)',
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
};
